-- MySQL Script generated by MySQL Workbench
-- Thu Oct 25 11:10:07 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_colegioprimaria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_colegioprimaria` ;

-- -----------------------------------------------------
-- Schema bd_colegioprimaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_colegioprimaria` DEFAULT CHARACTER SET utf8 ;
USE `bd_colegioprimaria` ;

-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`tipo_ambientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`tipo_ambientes` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`tipo_ambientes` (
  `Cod_TipoAmbiente` INT(11) NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(80) NULL DEFAULT NULL,
  `Estado` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_TipoAmbiente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`tipo_instituciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`tipo_instituciones` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`tipo_instituciones` (
  `Cod_tipoIE` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(20) NULL DEFAULT NULL,
  `Estado` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_tipoIE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`departamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`departamentos` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`departamentos` (
  `Cod_Departamento` CHAR(18) NOT NULL,
  `Descripcion` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_Departamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`provincias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`provincias` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`provincias` (
  `Cod_Provincia` CHAR(18) NOT NULL,
  `descripcion` VARCHAR(80) NULL DEFAULT NULL,
  `Cod_Departamento` CHAR(18) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_Provincia`),
  INDEX `R_55` (`Cod_Departamento` ASC),
  CONSTRAINT `provincias_ibfk_1`
    FOREIGN KEY (`Cod_Departamento`)
    REFERENCES `bd_colegioprimaria`.`departamentos` (`Cod_Departamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`distritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`distritos` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`distritos` (
  `Cod_distrito` CHAR(18) NOT NULL,
  `Descripcion` VARCHAR(80) NULL DEFAULT NULL,
  `Cod_Provincia` CHAR(18) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_distrito`),
  INDEX `R_56` (`Cod_Provincia` ASC),
  CONSTRAINT `distritos_ibfk_1`
    FOREIGN KEY (`Cod_Provincia`)
    REFERENCES `bd_colegioprimaria`.`provincias` (`Cod_Provincia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`instituciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`instituciones` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`instituciones` (
  `Cod_Institucion` INT(11) NOT NULL AUTO_INCREMENT,
  `Cod_modular` INT(11) NULL DEFAULT NULL,
  `Anexo` INT(11) NULL DEFAULT NULL,
  `Nivel` VARCHAR(80) NULL DEFAULT NULL,
  `Nombre` VARCHAR(80) NULL DEFAULT NULL,
  `Gestion` VARCHAR(80) NULL DEFAULT NULL,
  `Forma` VARCHAR(80) NULL DEFAULT NULL,
  `Codigo_local` INT(11) NULL DEFAULT NULL,
  `DRE` VARCHAR(80) NULL DEFAULT NULL,
  `UGEL` VARCHAR(80) NULL DEFAULT NULL,
  `Resolucion` VARCHAR(80) NULL DEFAULT NULL,
  `Emblematica` CHAR(2) NULL DEFAULT NULL,
  `Direccion` VARCHAR(80) NULL DEFAULT NULL,
  `Centro_Poblado` VARCHAR(80) NULL DEFAULT NULL,
  `Resolucion_IE` VARCHAR(80) NULL DEFAULT NULL,
  `Telefono` VARCHAR(9) NULL DEFAULT NULL,
  `Pagina_web` VARCHAR(80) NULL DEFAULT NULL,
  `Genero` VARCHAR(80) NULL DEFAULT NULL,
  `Correo` VARCHAR(80) NULL DEFAULT NULL,
  `Cod_tipoIE` INT(11) NULL DEFAULT NULL,
  `Cod_distrito` CHAR(18) NULL DEFAULT NULL,
  `Insignia` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_Institucion`),
  INDEX `R_58` (`Cod_tipoIE` ASC),
  INDEX `R_65` (`Cod_distrito` ASC),
  CONSTRAINT `instituciones_ibfk_1`
    FOREIGN KEY (`Cod_tipoIE`)
    REFERENCES `bd_colegioprimaria`.`tipo_instituciones` (`Cod_tipoIE`),
  CONSTRAINT `instituciones_ibfk_2`
    FOREIGN KEY (`Cod_distrito`)
    REFERENCES `bd_colegioprimaria`.`distritos` (`Cod_distrito`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`ambientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`ambientes` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`ambientes` (
  `Cod_ambiente` INT(11) NOT NULL AUTO_INCREMENT,
  `Cod_TipoAmbiente` INT NULL DEFAULT NULL,
  `Descripcion` VARCHAR(80) NULL DEFAULT NULL,
  `Ubicacion` VARCHAR(80) NULL DEFAULT NULL,
  `Aforo` INT NULL DEFAULT NULL,
  `Area` INT NULL DEFAULT NULL,
  `Estado` VARCHAR(20) NULL DEFAULT NULL,
  `Cod_Institucion` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_ambiente`),
  INDEX `R_59` (`Cod_TipoAmbiente` ASC),
  INDEX `R_63` (`Cod_Institucion` ASC),
  CONSTRAINT `ambientes_ibfk_1`
    FOREIGN KEY (`Cod_TipoAmbiente`)
    REFERENCES `bd_colegioprimaria`.`tipo_ambientes` (`Cod_TipoAmbiente`),
  CONSTRAINT `ambientes_ibfk_2`
    FOREIGN KEY (`Cod_Institucion`)
    REFERENCES `bd_colegioprimaria`.`instituciones` (`Cod_Institucion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`anio_escolar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`anio_escolar` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`anio_escolar` (
  `Cod_Escolar` INT(11) NOT NULL AUTO_INCREMENT,
  `Anio_escolar` INT(11) NULL DEFAULT NULL,
  `Fecha_Inicio` DATE NULL DEFAULT NULL,
  `Fecha_Fin` DATE NULL DEFAULT NULL,
  `Estado` VARCHAR(20) NULL DEFAULT NULL,
  `modalidad_evaluacion` VARCHAR(50) NULL DEFAULT NULL,
  `N_personalIE` INT(11) NULL DEFAULT NULL,
  `Cod_Institucion` INT(11) NOT NULL,
  PRIMARY KEY (`Cod_Escolar`, `Cod_Institucion`),
  INDEX `R_111` (`Cod_Institucion` ASC),
  CONSTRAINT `anio_escolar_ibfk_1`
    FOREIGN KEY (`Cod_Institucion`)
    REFERENCES `bd_colegioprimaria`.`instituciones` (`Cod_Institucion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`cursos` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`cursos` (
  `Cod_Cursos` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(20) NULL DEFAULT NULL,
  `N_Capacidades` INT(11) NULL DEFAULT NULL,
  `Estado` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_Cursos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`capacidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`capacidades` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`capacidades` (
  `Cod_Capacidades` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(80) NULL DEFAULT NULL,
  `Justificacion` VARCHAR(80) NULL DEFAULT NULL,
  `Cod_Cursos` INT(11) NOT NULL,
  PRIMARY KEY (`Cod_Capacidades`, `Cod_Cursos`),
  INDEX `R_99` (`Cod_Cursos` ASC),
  CONSTRAINT `capacidades_ibfk_1`
    FOREIGN KEY (`Cod_Cursos`)
    REFERENCES `bd_colegioprimaria`.`cursos` (`Cod_Cursos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`disenio_curricular`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`disenio_curricular` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`disenio_curricular` (
  `Cod_DisenioC` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(50) NULL DEFAULT NULL,
  `Anio` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_DisenioC`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`grados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`grados` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`grados` (
  `Cod_Grados` INT(11) NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(50) NULL DEFAULT NULL,
  `N_secciones` INT(11) NULL DEFAULT NULL,
  `N_Cursos` INT(11) NULL DEFAULT NULL,
  `Cod_DisenioC` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_Grados`),
  INDEX `R_140` (`Cod_DisenioC` ASC),
  CONSTRAINT `grados_ibfk_1`
    FOREIGN KEY (`Cod_DisenioC`)
    REFERENCES `bd_colegioprimaria`.`disenio_curricular` (`Cod_DisenioC`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`tipos_periodos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`tipos_periodos` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`tipos_periodos` (
  `Cod_Tipo` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_Tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`periodos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`periodos` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`periodos` (
  `Cod_Periodos` INT(11) NOT NULL AUTO_INCREMENT,
  `N_Descripcion` VARCHAR(15) NULL DEFAULT NULL,
  `Anio_Escolar` DATE NULL DEFAULT NULL,
  `Cod_Tipo` INT(11) NULL DEFAULT NULL,
  `Descripcion_periodo` VARCHAR(20) NULL DEFAULT NULL,
  `Fecha_inicio` DATE NULL DEFAULT NULL,
  `Fecha_Fin` DATE NULL DEFAULT NULL,
  `Estado` VARCHAR(20) NULL DEFAULT NULL,
  `Cod_Escolar` INT(11) NOT NULL,
  `Cod_Institucion` INT(11) NOT NULL,
  PRIMARY KEY (`Cod_Periodos`, `Cod_Escolar`, `Cod_Institucion`),
  INDEX `R_49` (`Cod_Tipo` ASC),
  INDEX `R_112` (`Cod_Escolar` ASC, `Cod_Institucion` ASC),
  CONSTRAINT `periodos_ibfk_1`
    FOREIGN KEY (`Cod_Tipo`)
    REFERENCES `bd_colegioprimaria`.`tipos_periodos` (`Cod_Tipo`),
  CONSTRAINT `periodos_ibfk_2`
    FOREIGN KEY (`Cod_Escolar` , `Cod_Institucion`)
    REFERENCES `bd_colegioprimaria`.`anio_escolar` (`Cod_Escolar` , `Cod_Institucion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`cursos_grados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`cursos_grados` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`cursos_grados` (
  `Cod_Cursos` INT(11) NOT NULL,
  `Cod_Grados` INT(11) NOT NULL,
  `Observacion` VARCHAR(80) NULL DEFAULT NULL,
  `Cod_Periodos` INT(11) NOT NULL,
  `Cod_Escolar` INT(11) NOT NULL,
  `Cod_Institucion` INT(11) NOT NULL,
  PRIMARY KEY (`Cod_Cursos`, `Cod_Grados`, `Cod_Periodos`, `Cod_Escolar`, `Cod_Institucion`),
  INDEX `R_96` (`Cod_Grados` ASC),
  INDEX `R_118` (`Cod_Periodos` ASC, `Cod_Escolar` ASC, `Cod_Institucion` ASC),
  CONSTRAINT `cursos_grados_ibfk_1`
    FOREIGN KEY (`Cod_Cursos`)
    REFERENCES `bd_colegioprimaria`.`cursos` (`Cod_Cursos`),
  CONSTRAINT `cursos_grados_ibfk_2`
    FOREIGN KEY (`Cod_Grados`)
    REFERENCES `bd_colegioprimaria`.`grados` (`Cod_Grados`),
  CONSTRAINT `cursos_grados_ibfk_3`
    FOREIGN KEY (`Cod_Periodos` , `Cod_Escolar` , `Cod_Institucion`)
    REFERENCES `bd_colegioprimaria`.`periodos` (`Cod_Periodos` , `Cod_Escolar` , `Cod_Institucion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`personas` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`personas` (
  `Cod_Persona` INT(11) NOT NULL AUTO_INCREMENT,
  `Ape_Paterno` VARCHAR(80) NULL DEFAULT NULL,
  `Ape_Materno` VARCHAR(80) NULL DEFAULT NULL,
  `Nombres` VARCHAR(80) NULL DEFAULT NULL,
  `Sexo` CHAR(1) NULL DEFAULT NULL,
  `Estado_civil` VARCHAR(15) NULL DEFAULT NULL,
  `Fecha_Nac` DATE NULL DEFAULT NULL,
  `Direccion` VARCHAR(80) NULL DEFAULT NULL,
  `Telefono` INT(9) NULL DEFAULT NULL,
  `Correo` VARCHAR(50) NULL DEFAULT NULL,
  `Cod_distrito` CHAR(18) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_Persona`),
  INDEX `R_57` (`Cod_distrito` ASC),
  CONSTRAINT `personas_ibfk_1`
    FOREIGN KEY (`Cod_distrito`)
    REFERENCES `bd_colegioprimaria`.`distritos` (`Cod_distrito`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`docentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`docentes` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`docentes` (
  `Cod_Persona` INT(11) NOT NULL,
  `Cargo` VARCHAR(50) NULL DEFAULT NULL,
  `Funcion` VARCHAR(50) NULL DEFAULT NULL,
  `Estado` CHAR(1) NULL DEFAULT NULL,
  `Nivel_Instruccion` VARCHAR(50) NULL DEFAULT NULL,
  `Carrera_Profesional` VARCHAR(50) NULL DEFAULT NULL,
  `Fecha_Inicio` DATE NULL DEFAULT NULL,
  `Fecha_Fin` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_Persona`),
  CONSTRAINT `docentes_ibfk_1`
    FOREIGN KEY (`Cod_Persona`)
    REFERENCES `bd_colegioprimaria`.`personas` (`Cod_Persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`docentes_cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`docentes_cursos` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`docentes_cursos` (
  `Cod_Persona` INT(11) NOT NULL,
  `Cod_Cursos` INT(11) NOT NULL,
  PRIMARY KEY (`Cod_Persona`, `Cod_Cursos`),
  INDEX `R_104` (`Cod_Cursos` ASC),
  CONSTRAINT `docentes_cursos_ibfk_1`
    FOREIGN KEY (`Cod_Persona`)
    REFERENCES `bd_colegioprimaria`.`docentes` (`Cod_Persona`),
  CONSTRAINT `docentes_cursos_ibfk_2`
    FOREIGN KEY (`Cod_Cursos`)
    REFERENCES `bd_colegioprimaria`.`cursos` (`Cod_Cursos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`evaluaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`evaluaciones` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`evaluaciones` (
  `Cod_Evaluacion` INT(11) NOT NULL AUTO_INCREMENT,
  `Promedio_final` CHAR(2) NULL DEFAULT NULL,
  `Cod_Persona` INT(11) NULL DEFAULT NULL,
  `Cod_Cursos` INT(11) NULL DEFAULT NULL,
  `Fecha` DATE NULL DEFAULT NULL,
  `Hora` TIME NULL DEFAULT NULL,
  `Cod_Grados` INT(11) NULL DEFAULT NULL,
  `Cod_Periodos` INT(11) NULL DEFAULT NULL,
  `Cod_Escolar` INT(11) NULL DEFAULT NULL,
  `Cod_Institucion` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_Evaluacion`),
  INDEX `R_113` (`Cod_Persona` ASC, `Cod_Cursos` ASC),
  INDEX `R_120` (`Cod_Cursos` ASC, `Cod_Grados` ASC, `Cod_Periodos` ASC, `Cod_Escolar` ASC, `Cod_Institucion` ASC),
  CONSTRAINT `evaluaciones_ibfk_1`
    FOREIGN KEY (`Cod_Persona` , `Cod_Cursos`)
    REFERENCES `bd_colegioprimaria`.`docentes_cursos` (`Cod_Persona` , `Cod_Cursos`),
  CONSTRAINT `evaluaciones_ibfk_2`
    FOREIGN KEY (`Cod_Cursos` , `Cod_Grados` , `Cod_Periodos` , `Cod_Escolar` , `Cod_Institucion`)
    REFERENCES `bd_colegioprimaria`.`cursos_grados` (`Cod_Cursos` , `Cod_Grados` , `Cod_Periodos` , `Cod_Escolar` , `Cod_Institucion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`discapacidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`discapacidades` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`discapacidades` (
  `Cod_Discapacidad` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_Discapacidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`estudiantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`estudiantes` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`estudiantes` (
  `Cod_Persona` INT(11) NOT NULL,
  `N_Hermanos` INT(11) NULL DEFAULT NULL,
  `Lugar_Ocupa` INT(11) NULL DEFAULT NULL,
  `Religion` VARCHAR(50) NULL DEFAULT NULL,
  `SAANEE` CHAR(2) NULL DEFAULT NULL,
  `Frecuencia_Saanee` VARCHAR(15) NULL DEFAULT NULL,
  `Cod_Discapacidad` INT(11) NULL DEFAULT NULL,
  `Cod_Estudiante` CHAR(14) NOT NULL,
  PRIMARY KEY (`Cod_Persona`, `Cod_Estudiante`),
  INDEX `R_16` (`Cod_Discapacidad` ASC),
  CONSTRAINT `estudiantes_ibfk_1`
    FOREIGN KEY (`Cod_Persona`)
    REFERENCES `bd_colegioprimaria`.`personas` (`Cod_Persona`),
  CONSTRAINT `estudiantes_ibfk_2`
    FOREIGN KEY (`Cod_Discapacidad`)
    REFERENCES `bd_colegioprimaria`.`discapacidades` (`Cod_Discapacidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`turnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`turnos` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`turnos` (
  `Cod_Turnos` INT(11) NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_Turnos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`tipo_fase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`tipo_fase` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`tipo_fase` (
  `Cod_tipoFase` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(80) NULL DEFAULT NULL,
  `Estado` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_tipoFase`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`fases_escolares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`fases_escolares` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`fases_escolares` (
  `Cod_Fase` INT(11) NOT NULL AUTO_INCREMENT,
  `Cod_tipoFase` INT(11) NULL DEFAULT NULL,
  `Cod_Escolar` INT(11) NULL DEFAULT NULL,
  `Fecha_Desde` DATE NULL DEFAULT NULL,
  `Fecha_Hasta` DATE NULL DEFAULT NULL,
  `Permitir_Asistencia` VARCHAR(2) NULL DEFAULT NULL,
  `Estado` VARCHAR(20) NULL DEFAULT NULL,
  `Cod_Institucion` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_Fase`),
  INDEX `R_60` (`Cod_tipoFase` ASC),
  INDEX `R_61` (`Cod_Escolar` ASC, `Cod_Institucion` ASC),
  CONSTRAINT `fases_escolares_ibfk_1`
    FOREIGN KEY (`Cod_tipoFase`)
    REFERENCES `bd_colegioprimaria`.`tipo_fase` (`Cod_tipoFase`),
  CONSTRAINT `fases_escolares_ibfk_2`
    FOREIGN KEY (`Cod_Escolar` , `Cod_Institucion`)
    REFERENCES `bd_colegioprimaria`.`anio_escolar` (`Cod_Escolar` , `Cod_Institucion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`secciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`secciones` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`secciones` (
  `Cod_Secciones` INT(11) NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(30) NULL DEFAULT NULL,
  `Cod_Persona` INT(11) NULL DEFAULT NULL,
  `Cod_Turnos` INT(11) NULL DEFAULT NULL,
  `Cod_Fase` INT(11) NULL DEFAULT NULL,
  `Aforo` INT(11) NULL DEFAULT NULL,
  `RD_institucional` VARCHAR(30) NULL DEFAULT NULL,
  `Fecha_Aprobacion` DATE NULL DEFAULT NULL,
  `N_estudiantes` INT(11) NULL DEFAULT NULL,
  `Cod_Grados` INT(11) NOT NULL,
  PRIMARY KEY (`Cod_Secciones`, `Cod_Grados`),
  INDEX `R_72` (`Cod_Persona` ASC),
  INDEX `R_73` (`Cod_Turnos` ASC),
  INDEX `R_75` (`Cod_Fase` ASC),
  INDEX `R_82` (`Cod_Grados` ASC),
  CONSTRAINT `secciones_ibfk_1`
    FOREIGN KEY (`Cod_Persona`)
    REFERENCES `bd_colegioprimaria`.`docentes` (`Cod_Persona`),
  CONSTRAINT `secciones_ibfk_2`
    FOREIGN KEY (`Cod_Turnos`)
    REFERENCES `bd_colegioprimaria`.`turnos` (`Cod_Turnos`),
  CONSTRAINT `secciones_ibfk_3`
    FOREIGN KEY (`Cod_Fase`)
    REFERENCES `bd_colegioprimaria`.`fases_escolares` (`Cod_Fase`),
  CONSTRAINT `secciones_ibfk_4`
    FOREIGN KEY (`Cod_Grados`)
    REFERENCES `bd_colegioprimaria`.`grados` (`Cod_Grados`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`matriculas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`matriculas` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`matriculas` (
  `Cod_Persona` INT(11) NULL DEFAULT NULL,
  `Fecha_Matricula` DATE NULL DEFAULT NULL,
  `Repetir_grado` VARCHAR(10) NULL DEFAULT NULL,
  `Condicion_matricula` VARCHAR(20) NULL DEFAULT NULL,
  `Situacion_matricula` VARCHAR(30) NULL DEFAULT NULL,
  `Tipo_procedencia` VARCHAR(30) NULL DEFAULT NULL,
  `Observaciones` VARCHAR(80) NULL DEFAULT NULL,
  `Cod_Estudiante` CHAR(14) NULL DEFAULT NULL,
  `Cod_Matricula` INT(11) NOT NULL AUTO_INCREMENT,
  `Estado_matricula` VARCHAR(20) NULL DEFAULT NULL,
  `Descripcion_IE` VARCHAR(50) NULL DEFAULT NULL,
  `Cod_Secciones` INT(11) NULL DEFAULT NULL,
  `Cod_Grados` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_Matricula`),
  INDEX `R_17` (`Cod_Persona` ASC, `Cod_Estudiante` ASC),
  INDEX `R_116` (`Cod_Secciones` ASC, `Cod_Grados` ASC),
  CONSTRAINT `matriculas_ibfk_1`
    FOREIGN KEY (`Cod_Persona` , `Cod_Estudiante`)
    REFERENCES `bd_colegioprimaria`.`estudiantes` (`Cod_Persona` , `Cod_Estudiante`),
  CONSTRAINT `matriculas_ibfk_2`
    FOREIGN KEY (`Cod_Secciones` , `Cod_Grados`)
    REFERENCES `bd_colegioprimaria`.`secciones` (`Cod_Secciones` , `Cod_Grados`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`matriculas_cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`matriculas_cursos` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`matriculas_cursos` (
  `Cod_Matricula` INT(11) NOT NULL,
  `Cod_Persona` INT(11) NULL DEFAULT NULL,
  `Cod_Cursos` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_Matricula`),
  INDEX `R_130` (`Cod_Persona` ASC, `Cod_Cursos` ASC),
  CONSTRAINT `matriculas_cursos_ibfk_1`
    FOREIGN KEY (`Cod_Matricula`)
    REFERENCES `bd_colegioprimaria`.`matriculas` (`Cod_Matricula`),
  CONSTRAINT `matriculas_cursos_ibfk_2`
    FOREIGN KEY (`Cod_Persona` , `Cod_Cursos`)
    REFERENCES `bd_colegioprimaria`.`docentes_cursos` (`Cod_Persona` , `Cod_Cursos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`detalles_evaluaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`detalles_evaluaciones` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`detalles_evaluaciones` (
  `calificacion` CHAR(1) NULL DEFAULT NULL,
  `Cod_Evaluacion` INT(11) NOT NULL,
  `Cod_Matricula` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_Evaluacion`),
  INDEX `R_129` (`Cod_Matricula` ASC),
  CONSTRAINT `detalles_evaluaciones_ibfk_1`
    FOREIGN KEY (`Cod_Evaluacion`)
    REFERENCES `bd_colegioprimaria`.`evaluaciones` (`Cod_Evaluacion`),
  CONSTRAINT `detalles_evaluaciones_ibfk_2`
    FOREIGN KEY (`Cod_Matricula`)
    REFERENCES `bd_colegioprimaria`.`matriculas_cursos` (`Cod_Matricula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`tipo_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`tipo_documento` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`tipo_documento` (
  `Cod_Documento` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_Documento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`tipo_documento_personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`tipo_documento_personas` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`tipo_documento_personas` (
  `Cod_Documento` INT(11) NOT NULL,
  `Cod_Persona` INT(11) NOT NULL,
  `Numero_Identidad` VARCHAR(15) NULL,
  PRIMARY KEY (`Cod_Documento`, `Cod_Persona`),
  INDEX `R_10` (`Cod_Persona` ASC),
  UNIQUE INDEX `Numero_Identidad_UNIQUE` (`Numero_Identidad` ASC),
  CONSTRAINT `tipo_documento_personas_ibfk_1`
    FOREIGN KEY (`Cod_Documento`)
    REFERENCES `bd_colegioprimaria`.`tipo_documento` (`Cod_Documento`),
  CONSTRAINT `tipo_documento_personas_ibfk_2`
    FOREIGN KEY (`Cod_Persona`)
    REFERENCES `bd_colegioprimaria`.`personas` (`Cod_Persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_colegioprimaria`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_colegioprimaria`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `bd_colegioprimaria`.`usuarios` (
  `Cod_Persona` INT(11) NOT NULL,
  `Nombre_Usuario` VARCHAR(50) NULL DEFAULT NULL,
  `Contrasenia` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_Persona`),
  UNIQUE INDEX `Cod_Persona_UNIQUE` (`Cod_Persona` ASC),
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`Cod_Persona`)
    REFERENCES `bd_colegioprimaria`.`personas` (`Cod_Persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
