#UTILIZAMOS LA BASE DE DATOS

USE BD_COLEGIOPRIMARIA;

# ----------------------------------------------------
# INSERCIONES DE LA TABLA DEPARTAMENTOS
# ----------------------------------------------------
INSERT INTO DEPARTAMENTOS (COD_DEPARTAMENTO, DESCRIPCION) VALUES ('DP00001','ICA');

SELECT * FROM DEPARTAMENTOS;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA PROVINCIAS
# ----------------------------------------------------
INSERT INTO PROVINCIAS (COD_PROVINCIA, DESCRIPCION, COD_DEPARTAMENTO) VALUES ('PR00001','CHINCHA', 'DP00001');

SELECT * FROM `Provincias`  WHERE Cod_Departamento = 'DP00001';



# ----------------------------------------------------
# INSERCIONES DE LA TABLA DISTRITOS
# ----------------------------------------------------
INSERT INTO DISTRITOS (COD_DISTRITO, DESCRIPCION, COD_PROVINCIA) VALUES ('D009701','CHICNHA ALTA', 'PR00001');
INSERT INTO DISTRITOS (COD_DISTRITO, DESCRIPCION, COD_PROVINCIA) VALUES ('D009702','CHICNHA BAJA', 'PR00001');
INSERT INTO DISTRITOS (COD_DISTRITO, DESCRIPCION, COD_PROVINCIA) VALUES ('D009703','ALTO LARAN', 'PR00001');
INSERT INTO DISTRITOS (COD_DISTRITO, DESCRIPCION, COD_PROVINCIA) VALUES ('D009704','EL CARMEN', 'PR00001');
INSERT INTO DISTRITOS (COD_DISTRITO, DESCRIPCION, COD_PROVINCIA) VALUES ('D009705','GROCIO PRADO', 'PR00001');
INSERT INTO DISTRITOS (COD_DISTRITO, DESCRIPCION, COD_PROVINCIA) VALUES ('D009706','SUNAMPE', 'PR00001');
INSERT INTO DISTRITOS (COD_DISTRITO, DESCRIPCION, COD_PROVINCIA) VALUES ('D009707','PUEBLO NUEVO', 'PR00001');
INSERT INTO DISTRITOS (COD_DISTRITO, DESCRIPCION, COD_PROVINCIA) VALUES ('D009708','TAMBO DE MORA', 'PR00001');
INSERT INTO DISTRITOS (COD_DISTRITO, DESCRIPCION, COD_PROVINCIA) VALUES ('D009709','SAN JUAN DE YANAC', 'PR00001');
INSERT INTO DISTRITOS (COD_DISTRITO, DESCRIPCION, COD_PROVINCIA) VALUES ('D009710','SAN PEDRO DE HUACARPANA', 'PR00001');
INSERT INTO DISTRITOS (COD_DISTRITO, DESCRIPCION, COD_PROVINCIA) VALUES ('D009711','CHAVIN', 'PR00001');

SELECT * FROM DISTRITOS;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: TIPOS_INSTITUCIONES
# ----------------------------------------------------
INSERT INTO TIPO_INSTITUCIONES(DESCRIPCION, ESTADO) VALUES ('PUBLICA','1');
INSERT INTO TIPO_INSTITUCIONES(DESCRIPCION, ESTADO) VALUES ('PRIVADA','1');

SELECT * FROM TIPO_INSTITUCIONES;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: INSTITUCIONES
# ----------------------------------------------------
INSERT INTO INSTITUCIONES(COD_MODULAR, ANEXO, NIVEL, NOMBRE, GESTION, FORMA, CODIGO_LOCAL, 
						  DRE, UGEL, RESOLUCION, EMBLEMATICA, DIRECCION, CENTRO_POBLADO, RESOLUCION_IE, 
                          TELEFONO, PAGINA_WEB, GENERO, CORREO, COD_TIPOIE, COD_DISTRITO, INSIGNIA) 
VALUES (1427678,156,'Primaria','Fe y Alegria N°30','-','Escolarizado',523725,'-','-','-','No','Jiron Lima S/N','AA.HH San Isidro','1489-GREJ','200245','-','Mixto','-','1','D009707','');

INSERT INTO INSTITUCIONES(COD_MODULAR, ANEXO, NIVEL, NOMBRE, GESTION, FORMA, CODIGO_LOCAL, 
						  DRE, UGEL, RESOLUCION, EMBLEMATICA, DIRECCION, CENTRO_POBLADO, RESOLUCION_IE, 
                          TELEFONO, PAGINA_WEB, GENERO, CORREO, COD_TIPOIE, COD_DISTRITO, INSIGNIA) 
VALUES (1524874,1564,'Primaria','Jose Yataco Pachas','-','Escolarizado',548712,'-','-','-','No','Avenida 13 de Octubre','AA.HH 13 de Octubre','1445-GREJ','154771','-','Mixto','-','1','D009707','');

INSERT INTO INSTITUCIONES(COD_MODULAR, ANEXO, NIVEL, NOMBRE, GESTION, FORMA, CODIGO_LOCAL, 
						  DRE, UGEL, RESOLUCION, EMBLEMATICA, DIRECCION, CENTRO_POBLADO, RESOLUCION_IE, 
                          TELEFONO, PAGINA_WEB, GENERO, CORREO, COD_TIPOIE, COD_DISTRITO, INSIGNIA) 
VALUES (1784751,4567,'Primaria','9 de Diciembre','-','Escolarizado',584874,'-','-','-','No','Avenida Primavera N° 478','AA.HH Primavera','1541-GREJ','458721','-','Mixto','-','1','D009707','');

SELECT * FROM INSTITUCIONES;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: TIPO_AMBIENTES
# ----------------------------------------------------
INSERT INTO TIPO_AMBIENTES (DESCRIPCION, ESTADO) VALUES ('NINGUNO','1');
INSERT INTO TIPO_AMBIENTES (DESCRIPCION, ESTADO) VALUES ('LABORATORIO','1');
INSERT INTO TIPO_AMBIENTES (DESCRIPCION, ESTADO) VALUES ('CENTRO DE COMPUTO','1');
INSERT INTO TIPO_AMBIENTES (DESCRIPCION, ESTADO) VALUES ('AULA DE MUSICA','1');
INSERT INTO TIPO_AMBIENTES (DESCRIPCION, ESTADO) VALUES ('ALMACEN','1');
INSERT INTO TIPO_AMBIENTES (DESCRIPCION, ESTADO) VALUES ('COCINA','1');

SELECT * FROM TIPO_AMBIENTES;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: AMBIENTES
# ----------------------------------------------------
INSERT INTO AMBIENTES (COD_TIPOAMBIENTE, DESCRIPCION, UBICACION, AFORO, AREA, ESTADO, COD_INSTITUCION) VALUES (2,'AULA GENERICA DE LA IE 1','PRIMER PISO',20,47,'BUENO',1);  -- PARA EL ESTADO ES BUENO, REGULAR, MALO
INSERT INTO AMBIENTES (COD_TIPOAMBIENTE, DESCRIPCION, UBICACION, AFORO, AREA, ESTADO, COD_INSTITUCION) VALUES (2,'AULA GENERICA DE LA IE 2','SEGUNDO PISO',30,52,'REGULAR',1);

SELECT * FROM AMBIENTES;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: ANIO_ESCOLAR
# ----------------------------------------------------
INSERT INTO ANIO_ESCOLAR (ANIO_ESCOLAR, FECHA_INICIO, FECHA_FIN, ESTADO, MODALIDAD_EVALUACION, N_PERSONALIE, COD_INSTITUCION) VALUES (2017,'2017-04-01','2017-12-30','ACTIVO','REGISTRO DE NOTAS FINAL',5,1);  -- PARA EL ESTADO ES INACTIVO, ACTIVO, CERRADO
INSERT INTO ANIO_ESCOLAR (ANIO_ESCOLAR, FECHA_INICIO, FECHA_FIN, ESTADO, MODALIDAD_EVALUACION, N_PERSONALIE, COD_INSTITUCION) VALUES (2018,'2018-04-01','2018-12-30','INACTIVO','REGITRO DE NOTAS',8,1);

SELECT * FROM ANIO_ESCOLAR;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: TIPO_DOCUMENTO
# ----------------------------------------------------
INSERT INTO TIPO_DOCUMENTO (DESCRIPCION) VALUES ('DNI'); -- 8 DIGITOS
INSERT INTO TIPO_DOCUMENTO (DESCRIPCION) VALUES ('CARNET DE EXTRANJERIA'); -- 12 DIGITOS
INSERT INTO TIPO_DOCUMENTO (DESCRIPCION) VALUES ('PASAPORTE'); -- 12 DIGITOS
INSERT INTO TIPO_DOCUMENTO (DESCRIPCION) VALUES ('PARTIDA DE NACIMIENTO'); -- 15 DIGITOS
INSERT INTO TIPO_DOCUMENTO (DESCRIPCION) VALUES ('OTROS'); -- 15 DIGITOS

SELECT * FROM TIPO_DOCUMENTO;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: PERSONAS
# ----------------------------------------------------
INSERT INTO PERSONAS (APE_PATERNO, APE_MATERNO, NOMBRES, SEXO, ESTADO_CIVIL, FECHA_NAC, DIRECCION, TELEFONO, CORREO, COD_DISTRITO) VALUES ('ARMAS', 'MAGALLANES', 'ROGGER', 'M', 'SOLTERO', '1992-08-14', 'JIRON ARICA S/N' ,'504144','ROGGERARMAS@GMAIL.COM', 'D009707'); 
INSERT INTO PERSONAS (APE_PATERNO, APE_MATERNO, NOMBRES, SEXO, ESTADO_CIVIL, FECHA_NAC, DIRECCION, TELEFONO, CORREO, COD_DISTRITO) VALUES ('DIAZ', 'REBATTA', 'VIVIANA', 'F', 'SOLTERO', '1992-06-06', 'AV. SAN MIGUEL' ,'145877','VIVIANADIAZ@GMAIL.COM', 'D009707'); 
INSERT INTO PERSONAS (APE_PATERNO, APE_MATERNO, NOMBRES, SEXO, ESTADO_CIVIL, FECHA_NAC, DIRECCION, TELEFONO, CORREO, COD_DISTRITO) VALUES ('CARO', 'COLQUEPISCO', 'CAMILO', 'M', 'SOLTERO', '1992-09-12', 'AV. SUCRE #150' ,'352141','CAMILOCARO@GMAIL.COM', 'D009707'); 

SELECT * FROM PERSONAS;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: TIPO_DOCUMENTO_PERSONAS
# ----------------------------------------------------
INSERT INTO TIPO_DOCUMENTO_PERSONAS (COD_DOCUMENTO, COD_PERSONA, NUMERO_IDENTIDAD) VALUES (1,1,'70337847'); -- 1 = DNI 
INSERT INTO TIPO_DOCUMENTO_PERSONAS (COD_DOCUMENTO, COD_PERSONA, NUMERO_IDENTIDAD) VALUES (2,2,'154845784145'); -- 2 = CARNET DE EXTRANJERIA
INSERT INTO TIPO_DOCUMENTO_PERSONAS (COD_DOCUMENTO, COD_PERSONA, NUMERO_IDENTIDAD) VALUES (3,3,'454748545448'); -- 3 = PASAPORTE

SELECT * FROM TIPO_DOCUMENTO_PERSONAS;

-- HACIENDO USO DE LOS INNER JOIN

SELECT T.DESCRIPCION, CONCAT(P.APE_PATERNO,' ',P.APE_MATERNO, ', ', P.NOMBRES) AS DATOS, TIP.NUMERO_IDENTIDAD FROM TIPO_DOCUMENTO_PERSONAS TIP
INNER JOIN TIPO_DOCUMENTO T ON TIP.COD_DOCUMENTO = T.COD_DOCUMENTO
INNER JOIN PERSONAS P ON TIP.COD_PERSONA = P.COD_PERSONA;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: DISCAPACIDADES
# ----------------------------------------------------
INSERT INTO DISCAPACIDADES (DESCRIPCION) VALUES ('NINGUNA');
INSERT INTO DISCAPACIDADES (DESCRIPCION) VALUES ('AUDITIVA'); 
INSERT INTO DISCAPACIDADES (DESCRIPCION) VALUES ('INTELECTUAL'); 
INSERT INTO DISCAPACIDADES (DESCRIPCION) VALUES ('MOTORA');  
INSERT INTO DISCAPACIDADES (DESCRIPCION) VALUES ('VISUAL'); 
INSERT INTO DISCAPACIDADES (DESCRIPCION) VALUES ('SORDOCEGUERA');  
INSERT INTO DISCAPACIDADES (DESCRIPCION) VALUES ('OTRA'); 
 
SELECT * FROM DISCAPACIDADES;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: ESTUDIANTES
# ----------------------------------------------------
INSERT INTO ESTUDIANTES (COD_PERSONA, N_HERMANOS, LUGAR_OCUPA, RELIGION, SAANEE, FRECUENCIA_SAANEE, COD_DISCAPACIDAD, COD_ESTUDIANTE) VALUES (1,3,3,'CATOLICA','NO','',1,'15487815457847');

SELECT * FROM ESTUDIANTES;

-- HACIENDO USO DEL INNER JOIN

SELECT P.COD_PERSONA, CONCAT(P.APE_PATERNO,' ',P.APE_MATERNO, ', ', P.NOMBRES) AS DATOS, EST.N_HERMANOS, EST.LUGAR_OCUPA, EST.RELIGION, EST.SAANEE, EST.FRECUENCIA_SAANEE, DIS.DESCRIPCION, EST.COD_ESTUDIANTE FROM ESTUDIANTES EST
INNER JOIN PERSONAS P ON EST.COD_PERSONA= P.COD_PERSONA
INNER JOIN DISCAPACIDADES DIS ON EST.COD_DISCAPACIDAD = DIS.COD_DISCAPACIDAD;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: TURNOS
# ----------------------------------------------------
INSERT INTO TURNOS (DESCRIPCION) VALUES ('MAÑANA');
INSERT INTO TURNOS (DESCRIPCION) VALUES ('TARDE');
INSERT INTO TURNOS (DESCRIPCION) VALUES ('NOCHE');
INSERT INTO TURNOS (DESCRIPCION) VALUES ('VESPERTINO');

SELECT * FROM TURNOS;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: DISEÑO CURRICULAR
# ----------------------------------------------------
INSERT INTO DISENIO_CURRICULAR (DESCRIPCION, ANIO) VALUES ('DISENIO CURRICULAR NACIONAL 2009', '2018-01-01');

SELECT * FROM DISENIO_CURRICULAR;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: GRADOS
# ----------------------------------------------------
INSERT INTO GRADOS (DESCRIPCION, N_SECCIONES, N_CURSOS, COD_DISENIOC) VALUES ('PRIMERO', '0','0' ,1);
INSERT INTO GRADOS (DESCRIPCION, N_SECCIONES, N_CURSOS, COD_DISENIOC) VALUES ('SEGUNDO', '0','0' ,1);
INSERT INTO GRADOS (DESCRIPCION, N_SECCIONES, N_CURSOS, COD_DISENIOC) VALUES ('TERCERO', '0','0' ,1);
INSERT INTO GRADOS (DESCRIPCION, N_SECCIONES, N_CURSOS, COD_DISENIOC) VALUES ('CUARTO', '0','0' ,1);
INSERT INTO GRADOS (DESCRIPCION, N_SECCIONES, N_CURSOS, COD_DISENIOC) VALUES ('QUINTO', '0','0' ,1);
INSERT INTO GRADOS (DESCRIPCION, N_SECCIONES, N_CURSOS, COD_DISENIOC) VALUES ('SEXTO', '0','0' ,1);

SELECT * FROM GRADOS;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: CURSOS
# ----------------------------------------------------
INSERT INTO CURSOS (DESCRIPCION, N_CAPACIDADES, ESTADO) VALUES ('MATEMATICA', '0','1');
INSERT INTO CURSOS (DESCRIPCION, N_CAPACIDADES, ESTADO) VALUES ('COMUNICACION', '0','1');
INSERT INTO CURSOS (DESCRIPCION, N_CAPACIDADES, ESTADO) VALUES ('PERSONAL SOCIAL', '0','1');

SELECT * FROM CURSOS;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: CAPACIDADES
# ----------------------------------------------------
INSERT INTO CAPACIDADES (DESCRIPCION, JUSTIFICACION, COD_CURSOS) VALUES ('PRACTICA ESCRITA', 'RESUELVE PROBLEMAS Y ACTIVIDADES',1);
INSERT INTO CAPACIDADES (DESCRIPCION, JUSTIFICACION, COD_CURSOS) VALUES ('PARTICIPACION Y DISCIPLINA', 'PARTICIPA DE LAS ACTIVIDADES DE LA MATERIA',1);
INSERT INTO CAPACIDADES (DESCRIPCION, JUSTIFICACION, COD_CURSOS) VALUES ('ACTITUD FRENTE AL AREA', 'COMPORTAMIENTO EN EL AULA',1);

SELECT * FROM CAPACIDADES;

-- HACIENDO USO DEL INNER JOIN

SELECT CAP.COD_CAPACIDADES, CAP.DESCRIPCION, CAP.JUSTIFICACION, CUR.DESCRIPCION AS CURSO FROM CAPACIDADES CAP
INNER JOIN CURSOS CUR ON CAP.COD_CURSOS = CUR.COD_CURSOS;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: DOCENTES
# ----------------------------------------------------
INSERT INTO DOCENTES (COD_PERSONA, CARGO, FUNCION, ESTADO, NIVEL_INSTRUCCION, CARRERA_PROFESIONAL, FECHA_INICIO, FECHA_FIN) VALUES (2,'DOCENTE POR HORAS','RESPONSABLE DE MATRICULA','1','EDUCACION UNIVERSITARIA','PSICOLOGIA','2017-03-01','2017-12-30');

SELECT * FROM DOCENTES;

-- HACIENDO USO DEL INNER JOIN

SELECT P.COD_PERSONA, CONCAT(P.APE_PATERNO,' ',P.APE_MATERNO, ', ', P.NOMBRES) AS DATOS, DOC.CARGO, DOC.FUNCION, DOC.NIVEL_INSTRUCCION, DOC.CARRERA_PROFESIONAL, DOC.FECHA_INICIO, DOC.FECHA_FIN FROM DOCENTES DOC
INNER JOIN PERSONAS P ON DOC.COD_PERSONA = P.COD_PERSONA;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: DOCENTES_CURSOS
# ----------------------------------------------------
INSERT INTO DOCENTES_CURSOS (COD_PERSONA, COD_CURSOS) VALUES (2,1);

SELECT * FROM DOCENTES_CURSOS;

-- HACIENDO USO DEL INNER JOIN

SELECT DOC.COD_PERSONA, CONCAT(P.APE_PATERNO,' ',P.APE_MATERNO, ', ', P.NOMBRES) AS DATOS, CUR.DESCRIPCION FROM DOCENTES_CURSOS DC
INNER JOIN DOCENTES DOC ON DC.COD_PERSONA = DOC.COD_PERSONA
INNER JOIN PERSONAS P ON DOC.COD_PERSONA = P.COD_PERSONA
INNER JOIN CURSOS CUR ON DC.COD_CURSOS = CUR.COD_CURSOS;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: TIPO_FASE
# ----------------------------------------------------
INSERT INTO TIPO_FASE (DESCRIPCION, ESTADO) VALUES ('FASE REGULAR','1');
INSERT INTO TIPO_FASE (DESCRIPCION, ESTADO) VALUES ('FASE DE RECUPERACION','1');

SELECT * FROM TIPO_FASE;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: FASES ESCOLARES
# ----------------------------------------------------
INSERT INTO FASES_ESCOLARES (COD_TIPOFASE, COD_ESCOLAR, FECHA_DESDE, FECHA_HASTA, PERMITIR_ASISTENCIA, ESTADO, COD_INSTITUCION)
VALUES (1,1,'2017-03-01','2017-12-30', 'SI', 'ACTIVO', 1);

SELECT * FROM FASES_ESCOLARES;
-- HACIENDO INNER JOIN

SELECT FE.COD_FASE, TF.DESCRIPCION, AE.ANIO_ESCOLAR, FE.FECHA_DESDE, FE.FECHA_HASTA, FE.PERMITIR_ASISTENCIA, FE.ESTADO, INS.NOMBRE FROM FASES_ESCOLARES FE
INNER JOIN TIPO_FASE TF ON FE.COD_TIPOFASE = TF.COD_TIPOFASE
INNER JOIN ANIO_ESCOLAR AE ON FE.COD_ESCOLAR = AE.COD_ESCOLAR
INNER JOIN INSTITUCIONES INS ON FE.COD_INSTITUCION = INS.COD_INSTITUCION;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: SECCIONES
# ----------------------------------------------------
INSERT INTO SECCIONES (DESCRIPCION, COD_PERSONA, COD_TURNOS, COD_FASE, AFORO, RD_INSTITUCIONAL, FECHA_APROBACION, N_ESTUDIANTES, COD_GRADOS)
VALUES ('A',2,1,1,25,'RD:2145','2017-02-25',0,1);


-- HACIENDO INNER JOIN
SELECT SEC.COD_SECCIONES, SEC.DESCRIPCION, CONCAT(P.APE_PATERNO,' ',P.APE_MATERNO, ', ', P.NOMBRES) AS TUTOR_DOCENTE,
	   TU.DESCRIPCION AS TURNO, TF.DESCRIPCION AS FASE, SEC.AFORO AS MAX_ESTUDIANTES, SEC.RD_INSTITUCIONAL, SEC.FECHA_APROBACION, SEC.N_ESTUDIANTES, 
	   G.DESCRIPCION AS GRADO FROM SECCIONES SEC
       
INNER JOIN DOCENTES DOC ON SEC.COD_PERSONA = DOC.COD_PERSONA
INNER JOIN PERSONAS P ON SEC.COD_PERSONA = P.COD_PERSONA
INNER JOIN TURNOS TU ON SEC.COD_TURNOS = TU.COD_TURNOS

INNER JOIN FASES_ESCOLARES FE ON SEC.COD_FASE = FE.COD_FASE
INNER JOIN TIPO_FASE TF ON FE.COD_TIPOFASE = TF.COD_TIPOFASE 

INNER JOIN GRADOS G ON SEC.COD_GRADOS = G.COD_GRADOS;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: MATRICULAS
# ----------------------------------------------------
INSERT INTO MATRICULAS
            (COD_PERSONA, FECHA_MATRICULA, REPETIR_GRADO, CONDICION_MATRICULA, SITUACION_MATRICULA, 
            TIPO_PROCEDENCIA, OBSERVACIONES, COD_ESTUDIANTE, ESTADO_MATRICULA, DESCRIPCION_IE, COD_SECCIONES,
            COD_GRADOS) 
VALUES (1,'2017-02-27', 'NO', 'GRATUITO', 'INGRESANTE', 'MISMA I.E', '-', '15487815457847', 'EN PROCESO','asdasd', 1,1);

SELECT * FROM MATRICULAS;

-- HACIENDO INNER JOIN

SELECT MAT.COD_MATRICULA, CONCAT(P.APE_PATERNO,' ',P.APE_MATERNO, ', ', P.NOMBRES) AS ESTUDIANTE,
	   MAT.FECHA_MATRICULA, MAT.REPETIR_GRADO, MAT.CONDICION_MATRICULA, MAT.SITUACION_MATRICULA, 
       MAT.TIPO_PROCEDENCIA, MAT.OBSERVACIONES, EST.COD_ESTUDIANTE, MAT.ESTADO_MATRICULA, MAT.DESCRIPCION_IE, 
       SEC.DESCRIPCION AS SECCION, G.DESCRIPCION AS GRADO
    FROM MATRICULAS MAT

INNER JOIN PERSONAS P ON MAT.COD_PERSONA = P.COD_PERSONA
INNER JOIN ESTUDIANTES EST ON MAT.COD_ESTUDIANTE = EST.COD_ESTUDIANTE
INNER JOIN SECCIONES SEC ON MAT.COD_SECCIONES = SEC.COD_SECCIONES
INNER JOIN GRADOS G ON MAT.COD_GRADOS = G.COD_GRADOS; 



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: TIPO_PERIODO
# ----------------------------------------------------
INSERT INTO TIPOS_PERIODOS (DESCRIPCION) VALUES ('ANUAL');
INSERT INTO TIPOS_PERIODOS (DESCRIPCION) VALUES ('BIMESTRAL');
INSERT INTO TIPOS_PERIODOS (DESCRIPCION) VALUES ('TRIMESTRAL');

SELECT * FROM TIPOS_PERIODOS;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: PERIODOS
# ----------------------------------------------------
INSERT INTO PERIODOS (N_DESCRIPCION, ANIO_ESCOLAR, COD_TIPO, DESCRIPCION_PERIODO, FECHA_INICIO, FECHA_FIN, ESTADO, COD_ESCOLAR, COD_INSTITUCION)
VALUES ('PRIMER BIMESTRE', '2017-03-01', 2, 'PRIMER BIMESTRE', '2017-03-01', '2017-12-30', 'SIN EVALUACION', 1,1);

SELECT * FROM PERIODOS;

-- HACIENDO USO DEL INNER JOIN
SELECT PER.COD_PERIODOS, PER.DESCRIPCION_PERIODO, PER.FECHA_INICIO, PER.FECHA_FIN, PER.ESTADO
FROM PERIODOS PER;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: CURSOS_GRADOS
# ----------------------------------------------------
INSERT INTO CURSOS_GRADOS (COD_CURSOS, COD_GRADOS, OBSERVACION, COD_PERIODOS, COD_ESCOLAR, COD_INSTITUCION)
VALUES (1,1,'APERTURAMOS EL CURSO PARA EL PRESENTE AÑO ACADEMICO',1,1,1);

SELECT * FROM CURSOS_GRADOS;

-- HACIENDO CONSULTA DE INNER JOIN

SELECT CUR.DESCRIPCION, G.DESCRIPCION, CG.OBSERVACION, PER.DESCRIPCION_PERIODO, 
	   AE.ANIO_ESCOLAR, INS.NOMBRE
FROM CURSOS_GRADOS CG
INNER JOIN CURSOS CUR ON CG.COD_CURSOS = CUR.COD_CURSOS
INNER JOIN GRADOS G ON CG.COD_GRADOS = G.COD_GRADOS
INNER JOIN PERIODOS PER ON CG.COD_PERIODOS = PER.COD_PERIODOS
INNER JOIN ANIO_ESCOLAR AE ON CG.COD_ESCOLAR = AE.COD_ESCOLAR
INNER JOIN INSTITUCIONES INS ON CG.COD_INSTITUCION = INS.COD_INSTITUCION;



# ----------------------------------------------------
# INSERCIONES DE LA TABLA: MATRICULAS_CURSOS
# ----------------------------------------------------
INSERT INTO MATRICULAS_CURSOS (COD_MATRICULA, COD_PERSONA, COD_CURSOS) VALUES (1,2,1);
SELECT * FROM MATRICULAS_CURSOS;

-- HACIENDO INNER JOIN
SELECT M.COD_MATRICULA, CONCAT(P.APE_PATERNO,' ',P.APE_MATERNO, ', ', P.NOMBRES) AS ESTUDIANTE, 
	   CONCAT(PP.APE_PATERNO,' ',PP.APE_MATERNO, ', ', PP.NOMBRES) AS DOCENTE, CUR.DESCRIPCION AS CURSO
       
FROM MATRICULAS_CURSOS MC

INNER JOIN MATRICULAS M  ON MC.COD_MATRICULA = M.COD_MATRICULA
-- INNER JOIN MATRICULAS M  ON EST.COD_PERSONA = M.COD_PERSONA
-- PARA RELACIONAR A ESTUDIANTES - PERSONAS
INNER JOIN ESTUDIANTES EST  ON M.COD_PERSONA = EST.COD_PERSONA
INNER JOIN PERSONAS P ON EST.COD_PERSONA = P.COD_PERSONA
-- PARA RELACIONAR A DOCENTES - PERRONAS
INNER JOIN DOCENTES DOS  ON MC.COD_PERSONA = DOS.COD_PERSONA
INNER JOIN PERSONAS PP ON DOS.COD_PERSONA = PP.COD_PERSONA
-- PARA RELACIONAR AL CURSO
INNER JOIN CURSOS CUR ON MC.COD_CURSOS = CUR.COD_CURSOS;