#UTILIZAMOS LA BASE DE DATOS
USE BD_COLEGIOPRIMARIA;

# PROCEDIMIENTO ALMACENADO PARA COMPETENCIAS
# PROCESO REGISTRO

DELIMITER $$
CREATE PROCEDURE Proc_registrar_competencias
(
    IN _DESCRIPCION		VARCHAR(80),
    IN _JUSTIFICACION	VARCHAR(80),
    IN _COD_CURSOS		INT(11)
)
BEGIN 
	insert into capacidades (descripcion, justificacion, cod_cursos) values (_DESCRIPCION, _JUSTIFICACION, _COD_CURSOS);
END
$$

CALL Proc_registrar_competencias('DEMUESTRA RESPONSABILIDAD', 'EL NIÑO DEMUESTRA LO APRENDIDO EN CLASES', 1);


# PROCESO MODIFICAR
DELIMITER $$
CREATE PROCEDURE Proc_modificar_competencias
(
	IN _COD_CAPACIDADES		INT(11),
	IN _DESCRIPCION			VARCHAR(80),
    IN _JUSTIFICACION		VARCHAR(80),
    IN _COD_CURSOS			INT(11)
)
begin 
	update capacidades set  DESCRIPCION = _DESCRIPCION,
							DESCRIPCION = _DESCRIPCION,
                            JUSTIFICACION = _JUSTIFICACION,
                            COD_CURSOS = _COD_CURSOS
    where COD_CAPACIDADES= _COD_CAPACIDADES;
end
$$

CALL Proc_modificar_competencias(1,'----','----',1);

# PROCESO ELIMINAR
DELIMITER $$
CREATE PROCEDURE Proc_eliminar_competencias
(
	IN _COD_CAPACIDADES		INT(11)
)
begin 
	Delete from capacidades where COD_CAPACIDADES = _COD_CAPACIDADES;
end
$$

CALL Proc_eliminar_competencias(1);


# PROCESO LISTAR
DELIMITER $$
CREATE PROCEDURE Proc_listar_competencias
(
)
begin 
	SELECT CAP.COD_CAPACIDADES, CAP.DESCRIPCION, CAP.JUSTIFICACION, CUR.DESCRIPCION AS CURSO FROM CAPACIDADES CAP
	INNER JOIN CURSOS CUR ON CAP.COD_CURSOS = CUR.COD_CURSOS;

end
$$


call Proc_listar_competencias();


# PROCESO BUSCAR
DELIMITER $$
CREATE PROCEDURE Proc_buscar_competencias
(
	IN _COD_CURSOS	INT(11)
)
begin 
	SELECT CAP.COD_CAPACIDADES, CAP.DESCRIPCION, CAP.JUSTIFICACION FROM CAPACIDADES CAP
	INNER JOIN CURSOS CUR ON CAP.COD_CURSOS = CUR.COD_CURSOS
    WHERE CAP.COD_CURSOS = _COD_CURSOS;
end
$$

call Proc_buscar_competencias(1);



# PROCESO LISTAR CURSOS
DELIMITER $$
CREATE PROCEDURE Proc_Listar_Cursos
()
begin 
	Select cod_cursos, descripcion from Cursos;
end
$$

call Proc_Listar_Cursos();