use bd_colegioprimaria;

#PROCEDIMIENTO ALMACENADO PARA REGISTRAR
DELIMITER $$
CREATE PROCEDURE Proc_insertar_cursos_grados
(
	IN _COD_CURSOS 			INT(11), 
    IN _COD_GRADOS			INT(11), 
    IN _OBSERVACION			VARCHAR(80), 
    IN _COD_PERIODOS 		INT(11), 
    IN _COD_ESCOLAR 		INT(11), 
    IN _COD_INSTITUCION		INT(11)
)
begin
	INSERT INTO CURSOS_GRADOS (COD_CURSOS, COD_GRADOS, OBSERVACION, COD_PERIODOS, COD_ESCOLAR, COD_INSTITUCION)
	VALUES (_COD_CURSOS,_COD_GRADOS,_OBSERVACION,_COD_PERIODOS,_COD_ESCOLAR,_COD_INSTITUCION);
end
$$

call Proc_insertar_cursos_grados(2,13,'APERTURAMOS EL CURSO PARA EL PRESENTE AÑO ACADEMICO',2,5,5);

# PROCEDIMIENTO ALMACENADO PARA BUSCAR

DELIMITER $$
CREATE PROCEDURE Proc_buscar_cursos_grados
(
	IN _COD_GRADOS 			INT(11)
)
begin
	SELECT CUR.DESCRIPCION AS CURSO, G.DESCRIPCION AS GRADO, CG.OBSERVACION, PER.DESCRIPCION_PERIODO, 
	   AE.ANIO_ESCOLAR, INS.NOMBRE
	FROM CURSOS_GRADOS CG
	INNER JOIN CURSOS CUR ON CG.COD_CURSOS = CUR.COD_CURSOS
	INNER JOIN GRADOS G ON CG.COD_GRADOS = G.COD_GRADOS
	INNER JOIN PERIODOS PER ON CG.COD_PERIODOS = PER.COD_PERIODOS
	INNER JOIN ANIO_ESCOLAR AE ON CG.COD_ESCOLAR = AE.COD_ESCOLAR
	INNER JOIN INSTITUCIONES INS ON CG.COD_INSTITUCION = INS.COD_INSTITUCION
WHERE CG.COD_GRADOS = _COD_GRADOS;
end
$$

-- buscamos mediante el call
call Proc_buscar_cursos_grados(1);
