#UTILIZAMOS LA BASE DE DATOS
USE BD_COLEGIOPRIMARIA;

# =========================================================	
# 	     PROCEDIMIENTOS ALMACENADOS - INSTITUCIONES
# =========================================================


# PROCEDIMIENTO ALMACENADO PARA REGISTRAR INSTITUCIONES
DELIMITER $$
CREATE PROCEDURE PROC_REGISTRAR_INSTITUCIONES
(
	IN	_COD_MODULAR          INTEGER,
	IN	_ANEXO                INTEGER,
	IN	_NIVEL                VARCHAR(80),
	IN	_NOMBRE               VARCHAR(80),
	IN	_GESTION              VARCHAR(80),
	IN	_FORMA                VARCHAR(80),
	IN	_CODIGO_LOCAL         INTEGER,
	IN	_DRE                  VARCHAR(80),
	IN	_UGEL                 VARCHAR(80),
	IN	_RESOLUCION           VARCHAR(80),
	IN	_EMBLEMATICA          CHAR(2),
	IN	_DIRECCION            VARCHAR(80),
	IN	_CENTRO_POBLADO       VARCHAR(80),
	IN	_RESOLUCION_IE        VARCHAR(40),
	IN	_TELEFONO             VARCHAR(9),
	IN	_PAGINA_WEB           VARCHAR(80),
	IN	_GENERO               VARCHAR(80),
	IN	_CORREO               VARCHAR(80),
	IN	_COD_TIPOIE           INT(11),
	IN	_COD_DISTRITO         CHAR(18),
	IN	_INSIGNIA             BLOB 
)
BEGIN
INSERT INTO INSTITUCIONES(COD_MODULAR, ANEXO, NIVEL, NOMBRE, GESTION, FORMA, CODIGO_LOCAL, 
						  DRE, UGEL, RESOLUCION, EMBLEMATICA, DIRECCION, CENTRO_POBLADO, RESOLUCION_IE, 
                          TELEFONO, PAGINA_WEB, GENERO, CORREO, COD_TIPOIE, COD_DISTRITO, INSIGNIA) 
VALUES (_COD_MODULAR, _ANEXO, _NIVEL, _NOMBRE, _GESTION, _FORMA, _CODIGO_LOCAL, 
						  _DRE, _UGEL, _RESOLUCION, _EMBLEMATICA, _DIRECCION, _CENTRO_POBLADO, _RESOLUCION_IE, 
                          _TELEFONO, _PAGINA_WEB, _GENERO, _CORREO, _COD_TIPOIE, _COD_DISTRITO, _INSIGNIA);
END
$$


# PROCEDIMIENTO ALMACENADO PARA EDITAR INSTITUCIONES
DELIMITER $$
CREATE PROCEDURE PROC_MODIFICAR_INSTITUCIONES
(
	IN  _COD_INSTITUCION   	  INT(11), 
	IN	_COD_MODULAR          INT(11),
	IN	_ANEXO                INT(11),
	IN	_NIVEL                VARCHAR(80),
	IN	_NOMBRE               VARCHAR(80),
	IN	_GESTION              VARCHAR(80),
	IN	_FORMA                VARCHAR(80),
	IN	_CODIGO_LOCAL         INT(11),
	IN	_DRE                  VARCHAR(80),
	IN	_UGEL                 VARCHAR(80),
	IN	_RESOLUCION           VARCHAR(80),
	IN	_EMBLEMATICA          CHAR(2),
	IN	_DIRECCION            VARCHAR(80),
	IN	_CENTRO_POBLADO       VARCHAR(80),
	IN	_RESOLUCION_IE        VARCHAR(40),
	IN	_TELEFONO             VARCHAR(9),
	IN	_PAGINA_WEB           VARCHAR(80),
	IN	_GENERO               VARCHAR(80),
	IN	_CORREO               VARCHAR(80),
	IN	_COD_TIPOIE           INT(11),
	IN	_COD_DISTRITO         CHAR(18),
	IN	_INSIGNIA             BLOB 
)
BEGIN 
	UPDATE INSTITUCIONES SET COD_MODULAR = _COD_MODULAR,
							 ANEXO = _ANEXO,
                             NIVEL = _NIVEL,
                             NOMBRE = _NOMBRE,
                             GESTION = _GESTION,
                             FORMA = _FORMA,
                             CODIGO_LOCAL = _CODIGO_LOCAL,
                             DRE = _DRE,
                             UGEL = _UGEL,
                             RESOLUCION = _RESOLUCION,
                             EMBLEMATICA = _EMBLEMATICA,
                             DIRECCION = _DIRECCION,
                             CENTRO_POBLADO = _CENTRO_POBLADO,
                             RESOLUCION_IE = _RESOLUCION_IE,
                             TELEFONO = _TELEFONO,
                             PAGINA_WEB = _PAGINA_WEB,
                             GENERO = _GENERO,
                             CORREO = _CORREO,
                             COD_TIPOIE = _COD_TIPOIE,
                             COD_DISTRITO = _COD_DISTRITO,
                             INSIGNIA = _INSIGNIA
	WHERE COD_INSTITUCION = _COD_INSTITUCION;
END
$$

# CALL PROC_MODIFICAR_INSTITUCIONES (1,456454,2165,'Primaria','Fe y Alegria N°30','-','Escolarizado',154875,'-','-','-','','','AA.HH San Isidro','1489-GREJ','200245','-','Mixto','-','1','D009707',''); 


# PROCEDIMIENTO ALMACENADO PARA ELIMINAR INSTITUCIONES
DELIMITER $$
CREATE PROCEDURE PROC_ELIMINAR_INSTITUCIONES
(
	IN _COD_INSTITUCION   	  INT(11)
)
BEGIN 
	DELETE FROM INSTITUCIONES WHERE COD_INSTITUCION = _COD_INSTITUCION;
END
$$

# CALL PROC_ELIMINAR_INSTITUCIONES(1);

# PROCEDIMIENTO ALMACENADO PARA LISTAR INSTITUCIONES
DELIMITER $$
CREATE PROCEDURE PROC_LISTAR_INSTITUCIONES
(
)
BEGIN
	SELECT INS.COD_INSTITUCION, INS.COD_MODULAR, INS.ANEXO, INS.NIVEL, INS.NOMBRE, INS.GESTION, INS.FORMA, INS.CODIGO_LOCAL, 
		   INS.DRE, INS.UGEL, INS.RESOLUCION, INS.EMBLEMATICA, INS.DIRECCION, INS.CENTRO_POBLADO, INS.RESOLUCION_IE, 
		   INS.TELEFONO, INS.PAGINA_WEB, INS.GENERO, INS.CORREO, TIP.DESCRIPCION AS TIPO_IE, DIS.DESCRIPCION AS DISTRITO, INS.INSIGNIA 
	FROM INSTITUCIONES INS
	INNER JOIN TIPO_INSTITUCIONES TIP ON INS.COD_TIPOIE = TIP.COD_TIPOIE
	INNER JOIN DISTRITOS DIS ON INS.COD_DISTRITO = DIS.COD_DISTRITO
    ORDER BY INS.COD_INSTITUCION ASC;
END
$$

CALL PROC_LISTAR_INSTITUCIONES();

# PROCEDIMIENTO ALMACENADO PARA FILTRAR INSTITUCIONES
DELIMITER $$
CREATE PROCEDURE PROC_FILTRAR_INSTITUCIONES
(
    IN _NOMBRES		VARCHAR(80)
)
BEGIN 
	 SELECT INS.COD_INSTITUCION, INS.COD_MODULAR, INS.ANEXO, INS.NIVEL, INS.NOMBRE, INS.GESTION, INS.FORMA, INS.CODIGO_LOCAL, 
		   INS.DRE, INS.UGEL, INS.RESOLUCION, INS.EMBLEMATICA, INS.DIRECCION, INS.CENTRO_POBLADO, INS.RESOLUCION_IE, 
		   INS.TELEFONO, INS.PAGINA_WEB, INS.GENERO, INS.CORREO, TIP.COD_TIPOIE,TIP.DESCRIPCION AS TIPO_IE, DIS.DESCRIPCION AS DISTRITO, INS.INSIGNIA 
	FROM INSTITUCIONES INS
	INNER JOIN TIPO_INSTITUCIONES TIP ON INS.COD_TIPOIE = TIP.COD_TIPOIE
	INNER JOIN DISTRITOS DIS ON INS.COD_DISTRITO = DIS.COD_DISTRITO
     WHERE (INS.NOMBRE Like CONCAT(_NOMBRES,'%'));
END
$$

CALL PROC_FILTRAR_INSTITUCIONES('');


# PROCEDIMIENTO ALMACENADO PARA FILTRAR INSTITUCIONES
DELIMITER $$
CREATE PROCEDURE PROC_BUSCAR_INSTITUCIONES
(
    IN _COD_INSTITUCION		INT(11)
)
BEGIN 
	 SELECT INS.COD_INSTITUCION, INS.COD_MODULAR, INS.ANEXO, INS.NIVEL, INS.NOMBRE, INS.GESTION, INS.FORMA, INS.CODIGO_LOCAL, 
		   INS.DRE, INS.UGEL, INS.RESOLUCION, INS.EMBLEMATICA, INS.DIRECCION, INS.CENTRO_POBLADO, INS.RESOLUCION_IE, 
		   INS.TELEFONO, INS.PAGINA_WEB, INS.GENERO, INS.CORREO, TIP.COD_TIPOIE, TIP.DESCRIPCION AS TIPO_IE, DIS.DESCRIPCION AS DISTRITO, INS.INSIGNIA 
	FROM INSTITUCIONES INS
	INNER JOIN TIPO_INSTITUCIONES TIP ON INS.COD_TIPOIE = TIP.COD_TIPOIE
	INNER JOIN DISTRITOS DIS ON INS.COD_DISTRITO = DIS.COD_DISTRITO
     WHERE INS.COD_INSTITUCION = _COD_INSTITUCION;
END
$$

CALL PROC_BUSCAR_INSTITUCIONES(1);