#UTILIZAMOS LA BASE DE DATOS
USE BD_COLEGIOPRIMARIA;

DELIMITER $$
CREATE PROCEDURE proc_registrar_PersonaDocumento
(
	IN _Cod_Documento		int(11),
    IN _Cod_Persona			int(11),
    IN _Numero_Identidad	Varchar(15)
)
BEGIN 
	INSERT INTO TIPO_DOCUMENTO_PERSONAS (COD_DOCUMENTO, COD_PERSONA, NUMERO_IDENTIDAD) 
    VALUES (_Cod_Documento,_Cod_Persona,_Numero_Identidad);
END
$$

DELIMITER $$
CREATE PROCEDURE proc_buscar_PersonaDocumento
(
	IN _Cod_Documento		int(11)
)
BEGIN
	SELECT T.DESCRIPCION, CONCAT(P.APE_PATERNO,' ',P.APE_MATERNO, ', ', P.NOMBRES) AS DATOS, TIP.NUMERO_IDENTIDAD FROM TIPO_DOCUMENTO_PERSONAS TIP
	INNER JOIN TIPO_DOCUMENTO T ON TIP.COD_DOCUMENTO = T.COD_DOCUMENTO
	INNER JOIN PERSONAS P ON TIP.COD_PERSONA = P.COD_PERSONA
    WHERE TIP.COD_DOCUMENTO = _Cod_Documento;
END
$$

CALL proc_buscar_PersonaDocumento(1);