#PROCEDIMIENTO BUSCAR

delimiter $$
create procedure buscar_matricula
(
	in _cod_matricula int(11)
)
begin
	SELECT MAT.COD_MATRICULA, CONCAT(P.APE_PATERNO,' ',P.APE_MATERNO, ', ', P.NOMBRES) AS ESTUDIANTE,
	   MAT.FECHA_MATRICULA, MAT.REPETIR_GRADO, MAT.CONDICION_MATRICULA, MAT.SITUACION_MATRICULA, 
       MAT.TIPO_PROCEDENCIA, MAT.OBSERVACIONES, EST.COD_ESTUDIANTE, MAT.ESTADO_MATRICULA, MAT.DESCRIPCION_IE, 
       SEC.DESCRIPCION AS SECCION, G.DESCRIPCION AS GRADO
    FROM MATRICULAS MAT

INNER JOIN PERSONAS P ON MAT.COD_PERSONA = P.COD_PERSONA
INNER JOIN ESTUDIANTES EST ON MAT.COD_ESTUDIANTE = EST.COD_ESTUDIANTE
INNER JOIN SECCIONES SEC ON MAT.COD_SECCIONES = SEC.COD_SECCIONES
INNER JOIN GRADOS G ON MAT.COD_GRADOS = G.COD_GRADOS
where  MAT.COD_MATRICULA = _cod_matricula;
end
$$

Call buscar_matricula(1);

