# AQUI ESTOY HACIENDO USO DELA BASE DE DATOS
USE BD_COLEGIOPRIMARIA;

# HACEMOS UN SELECT PARA VER SI HAY REGISTROS EN A TABLA TIPO_AMBIENTES

SELECT * FROM TIPO_AMBIENTES;


# PROCEDIMIENTO REGISTRAS

DELIMITER $$
CREATE PROCEDURE PROC_INSERTAR_TIPOSAMBIENTES
(
	IN _DESCRIPCION VARCHAR(80)
)
BEGIN
	INSERT INTO TIPO_AMBIENTES (DESCRIPCION, ESTADO) VALUES (_DESCRIPCION,'1');
END
$$


CALL PROC_INSERTAR_TIPOSAMBIENTES('muebles');


# PROCEDIMIENTO BUSCAR

DELIMITER $$
CREATE PROCEDURE PROC_BUSCAR_TIPOSAMBIENTES
(
	IN _DESCRIPCION VARCHAR(80)
)
BEGIN 
	SELECT COD_TIPOAMBIENTE, DESCRIPCION FROM TIPO_AMBIENTES
    WHERE  DESCRIPCION = _DESCRIPCION 
	AND  ESTADO = '1';
END
$$


CALL PROC_BUSCAR_TIPOSAMBIENTES('cocina');

# PROCEDIMIENTO LISTAR

DELIMITER $$
CREATE PROCEDURE PROC_LISTAR_TIPOSAMBIENTES
(
)
begin 
	SELECT COD_TIPOAMBIENTE, DESCRIPCION, ESTADO from TIPO_AMBIENTES
    where ESTADO='1';
end
$$

CALL PROC_LISTAR_TIPOSAMBIENTES();